config/routes.rb
Rails.application.routes.draw do
  resources :locals

end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all
  end

  # GET /locals/1
  # GET /locals/1.json
  def show
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1
  # PATCH/PUT /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locals_url, notice: 'Local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:c_mesa, :c_user, :n_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prototipo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locals/_form.html.erb
<%= form_for(@local) do |f| %>
  <% if @local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% @local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :c_mesa %><br>
    <%= f.text_field :c_mesa %>
  </div>
  <div class="field">
    <%= f.label :c_user %><br>
    <%= f.text_field :c_user %>
  </div>
  <div class="field">
    <%= f.label :n_user %><br>
    <%= f.text_field :n_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locals/edit.html.erb
<h1>Editing local</h1>

<%= render 'form' %>

<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>

app/views/locals/index.html.erb
<h1>Listing locals</h1>

<table>
  <thead>
    <tr>
      <th>C mesa</th>
      <th>C user</th>
      <th>N user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locals.each do |local| %>
      <tr>
        <td><%= local.c_mesa %></td>
        <td><%= local.c_user %></td>
        <td><%= local.n_user %></td>
        <td><%= link_to 'Show', local %></td>
        <td><%= link_to 'Edit', edit_local_path(local) %></td>
        <td><%= link_to 'Destroy', local, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Local', new_local_path %>

app/views/locals/new.html.erb
<h1>New local</h1>

<%= render 'form' %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>C mesa:</strong>
  <%= @local.c_mesa %>
</p>

<p>
  <strong>C user:</strong>
  <%= @local.c_user %>
</p>

<p>
  <strong>N user:</strong>
  <%= @local.n_user %>
</p>

<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>